### ISSUE TITLE
DirectoryNotFoundException: Could not find a part of the path 

### ISSUE THREAD

**Issue by aminos1941** [richardelms/FileBasedPlayerPrefs#11]
Hi

I always get this error 
DirectoryNotFoundException: Could not find a part of the path "/Users/xxx/Desktop/Unity Projects/xxx /my/explicit/savefile/pat/my-save-file.data".

The code is this (config) 

  // build your config
        var config = new FBPPConfig()
        {
            SaveFileName = "my-save-file.data",
            AutoSaveData = false,
            ScrambleSaveData = true,
            EncryptionSecret = "my-secret",
            SaveFilePath = "my/explicit/savefile/pat"
        };
        // pass it to FBPP
        FBPP.Start(config);

**Comment by aminos1941** [comment]
any news ?????

**Comment by rubenoriginal** [comment]
Reading at the code you posted it seems you just copied the explanatory one?
For example, this is what i used. I added an empty gameobject in the Main menu with this script it in.
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SaveData : MonoBehaviour
{
    void Awake()
    {
        var config = new FBPPConfig();
        {
            config.SaveFileName = "saveData.txt";
            config.AutoSaveData = true;
            config.ScrambleSaveData = false;
            config.SaveFilePath = Application.persistentDataPath;
        }

        FBPP.Start(config);
    }
}
```
You can change the settings to your liking, each setting is in the initialization part of the documentation.
