### ISSUE TITLE
Upgrading V1 to V2

### ISSUE THREAD

**Issue by chomi3** [richardelms/FileBasedPlayerPrefs#12]
Hey Richard,

Quick question - can I safely update my project (live) from V1 to V2?

I wouldn't like users to loose all their data.

I reviewed the code and it seems good to go, just wanted to double check this with you.

Thanks for your work.

Cheers
Mike

**Comment by richardelms** [comment]
sorry for the (checks watch 6 months later) late reply!
This should be fine, but if it was my game i would test it anyway
