### ISSUE TITLE
Users losing all their progress

### ISSUE THREAD

**Issue by pabloleban** [richardelms/FileBasedPlayerPrefs#2]
Hi Richard. First of all, thank you so much for making this awesome lib.

I wanted to point out that some users are losing all their progress with this library. Generally it occurs when the game closes unexpectedly.

On PC, some people report this that this happens when their power went off.

However, I'm still unable to reproduce the issue on my end. Do you have any idea why is this happening?

Thank you!

**Comment by Dknighter** [comment]
Hey,

This is also happening with my game. Whenever the game crashes the save files are being corrupted and made unusable.

Any fix for this would be greatly appreciated.

Thanks.

**Comment by NJBischoff** [comment]
Guys what I suggest you do is in FileBasedPrefsQuitListener.cs remove the call to save the fileprefs. In fact, I'd remove all those calls to the save method in focus, etc. Then rather call the save method yourself after you modify any data. That is the better way to do this anyway.

**Comment by Dknighter** [comment]
> Guys what I suggest you do is in FileBasedPrefsQuitListener.cs remove the call to save the fileprefs. In fact, I'd remove all those calls to the save method in focus, etc. Then rather call the save method yourself after you modify any data. That is the better way to do this anyway.

Hey, I'm using AutoSaveData instead of the quit listener.

**Comment by richardelms** [comment]
Hello

Sorry it took so long, but i just released V2 that includes instructions on how to make backups of your users data and how to restore it if a save file gets corrupted.

Good luck!
