### ISSUE TITLE
Manually Load Data and Steam User Saves

### ISSUE THREAD

**Issue by etherealgem** [richardelms/FileBasedPlayerPrefs#3]
Hi Richard,

I am using your FileBasedPlayerPrefs for a Steam game of mine and backing up the saved data to the cloud. So far, it works excellent, but I've run into an issue when trying to backup the data by _Steam User_. I have basically modified the saved data location in your script to navigate to " Application.persistentDataPath + "/" SteamManager.gameObject.GetComponent<SteamUsers>().SteamID...etc. + "/" " and it works, however, the Steam Manager must initialize _before_ I get the save file, since otherwise the "SteamID" will return 0. As a result, the FileBasedPlayerPrefs will write the file to the correct location, but not load from the correct location.

Do you know of any simple way to get around this? Is it possible to not load any FileBasedPlayerPrefs data until I decide to (i.e., after Steam intializes? Maybe via some code on the title screen instead of the splash screen?). The documentation explains how I can manually save the data, but not manually load it.

Thanks!

**Comment by richardelms** [comment]
Hello

I just released V2 that includes a new Start method that loads the data.
