### ISSUE TITLE
Not working on Oculus Quest (2)

### ISSUE THREAD

**Issue by smitdylan2001** [richardelms/FileBasedPlayerPrefs#6]
I do not get it working on Oculus Quest 2 (Android).
I don't see any errors in logcat, but it does not work at all. It does on Windows.

Using Unity 2020.3LTS

**Comment by richardelms** [comment]
Hi @smitdylan2001 can you give more information?

When you say it does not work at all, do you mean the data doesn't save and you always get back default values?

Unfortunately I don't have an Oculus Quest to test on 🤷

**Comment by smitdylan2001** [comment]
I looked online, and it might be due to JSONUtility not working on Android if IL2CPP is enabled. IL2CPP is crucial for my project, so I have not tested without it yet.

https://stackoverflow.com/questions/65440665/cannot-serialize-and-deserialize-json-in-unity
https://forum.unity.com/threads/resolved-il2cpp-error-when-use-simplejson-in-unity-5-1.332578/
https://stackoverflow.com/questions/59194154/newtonsoft-json-works-in-unity-editor-but-not-on-mobile-devices


Heard that this does work, testing it now:
https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347

**Comment by richardelms** [comment]
I just released V2 of the plugin.

JSONUtility works for me on IL2CPP android builds, i use it in all my apps.
