### ISSUE TITLE
FBPP.SetString() not consistently working

### ISSUE THREAD

**Issue by Laim** [richardelms/FileBasedPlayerPrefs#8]
This is a really weird one and there's absolutely no errors to come with it.  I want to save the level when the user hits their End Trigger, so I've put this in my `OnTriggerEnter2D` method

```csharp
        // if the last level
        if (SceneManager.GetActiveScene().buildIndex == SceneManager.sceneCountInBuildSettings - 1)
        {
            FBPP.SetString("LastLevel", sceneName);
            FBPP.Save();
            Debug.Log("Save current scene for last level");
        }
        else // if not the last level, i.e current scene
        {
            FBPP.SetString("LastLevel", nextSceneName);
            FBPP.Save();
            Debug.Log("Save next scene for last level");
        }
```

Just before this runs, I'm running `FBPP.SetInt("key", value)` and that is working consistently across plays and builds etc. 

Any idea why this wouldn't be saving?  It only seems to be with this one part as well, `SetString()` seems to work fine elsewhere, it's just on this one trigger.  Even doing `.Save();` afterwards to do it manually still doesn't save it, it's almost like it's completely ignoring the `SetString()`.

**Comment by Laim** [comment]
Oh, I'm on v2.0.2 as well.

**Comment by richardelms** [comment]
2 debugging ideas that might help

Could sceneName or nextSceneName be null?

A way to debug it would be to call FBPP.GetSaveFileAsJson(); and print that in a log, that will show the saved data and you can see if it's in there.

**Comment by richardelms** [comment]
Also, can you post the code where you read the value? If everything else is working fine, including GetString, then that suggests an issue with your implementation, and I can't help you fix that unless you share a lot more code.

**Comment by richardelms** [comment]
Closed due to no response or repro
